[[constraint]]
  name = "gopkg.in/yaml"
  version = "v2"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.3"

[[constraint]]
  name = "github.com/BurntSushi/toml"
  version = "0.3.0"

[[constraint]]
  name = "github.com/Masterminds/sprig"
  version = "2.14.0"